--Mostrar para cada vuelo lo siguiente:
--Cantidad de tripulantes
--Cantidad de puntos o escalas
--Cantidad de Asientos
--Cantidad de Pasajeros que pagaron
--Monto total de los tickets vendidos del vuelo.
--Quien es el piloto de ese vuelo

--NO HACER CRUCES ENTRE VARIAS TABLAS INTERMEDIAS    
      
SELECT *
FROM TBL_VUELOS;

SELECT A.CODIGO_VUELO, 
      A.CANTIDAD_TRIPULANTES,
      B.CANTIDAD_PUNTOS
FROM (
    SELECT CODIGO_VUELO, 
          COUNT(1) AS CANTIDAD_TRIPULANTES
    FROM TBL_TRIPULACION_X_VUELOS
    GROUP BY CODIGO_VUELO
) A
INNER JOIN (
    SELECT A.CODIGO_VUELO, 
          COUNT(1) CANTIDAD_PUNTOS
    FROM TBL_VUELOS A
    INNER JOIN TBL_RUTAS B
    ON (A.CODIGO_RUTA = B.CODIGO_RUTA)
    INNER JOIN TBL_PUNTOS_X_RUTAS C
    ON (B.CODIGO_RUTA = C.CODIGO_RUTA)
    GROUP BY A.CODIGO_VUELO
) B
ON (A.CODIGO_VUELO = B.CODIGO_VUELO);

SELECT CODIGO_VUELO, COUNT(1) AS CANTIDAD_TRIPULANTES
FROM TBL_TRIPULACION_X_VUELOS
GROUP BY CODIGO_VUELO;


        
SELECT A.CODIGO_VUELO, 
      COUNT(1) CANTIDAD_PUNTOS
FROM TBL_VUELOS A
INNER JOIN TBL_RUTAS B
ON (A.CODIGO_RUTA = B.CODIGO_RUTA)
INNER JOIN TBL_PUNTOS_X_RUTAS C
ON (B.CODIGO_RUTA = C.CODIGO_RUTA)
GROUP BY A.CODIGO_VUELO;

SELECT * 
FROM TBL_RUTAS;

SELECT *
FROM TBL_PUNTOS_X_RUTAS;

SELECT *
FROM TBL_PUNTO_ESCALA;