--Mostrar la cantidad de empleados por departamento.

--NVL verifica si el primer parametro es nulo, en caso de 
--ser asi, sustuye el valor por el segundo parametro.
SELECT  A.DEPARTMENT_ID, 
        NVL(B.DEPARTMENT_NAME,'Ninguno') as DEPARTMENT_NAME, 
        COUNT(1) AS CANTIDAD_EMPLEADOS
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
GROUP BY A.DEPARTMENT_ID, NVL(B.DEPARTMENT_NAME,'Ninguno')
ORDER BY DEPARTMENT_NAME;

--Mostrar los departamentos que tienen mas de 5 empleados, 
--para dichos departamentos mostrar la cantidad de empleados
-- y el salario invertido por cada departamento.

SELECT  A.DEPARTMENT_ID, 
        NVL(B.DEPARTMENT_NAME,'Ninguno') as DEPARTMENT_NAME, 
        COUNT(1) AS CANTIDAD_EMPLEADOS,
        SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
GROUP BY A.DEPARTMENT_ID, NVL(B.DEPARTMENT_NAME,'Ninguno')
HAVING COUNT(1)>5
ORDER BY DEPARTMENT_NAME;

--Mostrar el salario total por cada region sin perder ningun centavo.
SELECT NVL(E.REGION_NAME,'NO ASIGNADO') AS REGION_NAME, 
      SUM(A.SALARY)
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
LEFT JOIN LOCATIONS C
ON (B.LOCATION_ID = C.LOCATION_ID)
LEFT JOIN COUNTRIES D
ON (C.COUNTRY_ID = D.COUNTRY_ID)
LEFT JOIN REGIONS E
ON (D.REGION_ID = E.REGION_ID)
GROUP BY NVL(E.REGION_NAME,'NO ASIGNADO');


SELECT 321000 + 2686153 -- 3007153
FROM DUAL;


SELECT SUM(SALARY) --3014153
FROM EMPLOYEES;

SELECT 3007153-3014153
FROM DUAL;

SELECT *
FROM EMPLOYEES
WHERE SALARY = 7000;

SELECT *
FROM COUNTRIES
WHERE REGION_ID IS NULL;

SELECT *
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;

SELECT *
FROM REGIONS;
